### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ipAddress' at row 1

### ISSUE THREAD

**Issue by yassinrais** [sitchi/simple-admin-phalcon#1]
:) Somthing to fix here 👍 
```
#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\AbstractPdo->execute('INSERT INTO `us...', Array, Array)
#3 [internal function]: Phalcon\Db\Adapter\AbstractAdapter->insert('users_auths', Array, Array, Array)
#4 [internal function]: Phalcon\Mvc\Model->_doLowInsert(Object(Phalcon\Mvc\Model\MetaData\Memory), Object(Phalcon\Db\Adapter\Pdo\Mysql), 'users_auths', 'id')
#5 /var/www/simple-admin.sitchi.dev/app/library/Auth/Auth.php(89): Phalcon\Mvc\Model->save()
#6 /var/www/simple-admin.sitchi.dev/app/library/Auth/Auth.php(55): PSA\Auth\Auth->saveSuccessLogin(Object(PSA\Models\Users))
#7 /var/www/simple-admin.sitchi.dev/app/controllers/IndexController.php(50): PSA\Auth\Auth->check(Array)
#8 [internal function]: PSA\Controllers\IndexController->indexAction()
#9 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(PSA\Controllers\IndexController), 'indexAction', Array)
#10 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#11 /var/www/simple-admin.sitchi.dev/public/index.php(43): Phalcon\Mvc\Application->handle('/')
#12 {main}
```
**SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ipAddress' at row 1**

**Comment by sitchi** [comment]
@yassinrais Thank. this problem is fixed

**Comment by sitchi** [comment]
@yassinrais Thank. this problem is fixed
